#!/usr/bin/env bash
# Script that downloads a file from a server to our client
if [ $# -eq 4 ]
then
    scp -i "$4" -o StrictHostKeyChecking=no "$3"'@'"$2":~/"$1" ./
else
    echo "Usage: 0-download_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi