#!/usr/bin/env bash
# Script that downloads a file from a server to our client
if [ $# -eq 1 ]
then
    scp -i ~/.ssh/holberton -o StrictHostKeyChecking=no ubuntu@104.196.104.147:~/"$1" ./
else
    echo "Usage: 0-download_file_from_906-web-01 PATH_TO_FILE"
fi
