#!/usr/bin/env bash
# Script that downloads a file from a server to our client
if [ $# -eq 1 ]
then
    scp -i ~/.ssh/holberton -o StrictHostKeyChecking=no ubuntu@34.74.24.200:~/"$1" ./
else
    echo "Usage: 0-download_file_from_906-lb-01 PATH_TO_FILE"
fi
